tools:
    shell:
        allow:
            - find *
            - head *
            - ls *
            - wc *
            - uniq *
            - sort *
            - grep *
            - cd *
            - go build *
            - docker build *
            - file *
            - rm *
            - echo *
